### ISSUE TITLE
Add core team members data

### ISSUE THREAD

**Issue by HKAgrwl** [coding-club-iit-jammu/ClubWebsite#15]
Add data of core team members and Advising Committee in about.jsx -> teamCards.jsx using prop values.

**Comment by aaravjn** [comment]
What should I put in place of the data prop value?

**Comment by aaravjn** [comment]
Also, Should I create a new prop value for the branch and photo?

**Comment by HKAgrwl** [comment]
You can use the desc prop for branch and I think there's an img prop for photo.if not then you can create one.

**Comment by aaravjn** [comment]
The photos are taking time to get imported from the google drive links so should I download them, and then paste them into the site?

**Comment by HKAgrwl** [comment]
Sure, I was also thinking that it would be more efficient to keep the images in local storage.You can keep than inside a subfolder in "assets" folder...

**Comment by aaravjn** [comment]
Ya, but please ask everyone to upload their photos, and also ask them to provide access to their photos, as the ones who have provided the link have not made their photos publicly accessible...
