### ISSUE TITLE
Add the events page.

### ISSUE THREAD

**Issue by codingClub-iitjammu** [coding-club-iit-jammu/ClubWebsite#4]
Add events page for the website.

**Comment by kapiswayprakhar15** [comment]
Done

**Comment by codingClub-iitjammu** [comment]
can you please share screenshot of the events page?

**Comment by kapiswayprakhar15** [comment]
![event2](https://user-images.githubusercontent.com/110300128/208245088-9e2b88c4-416d-4d15-bfd6-0dccdec4dce8.png)
![Event](https://user-images.githubusercontent.com/110300128/208245090-98b90a41-1f53-4d1c-8b16-a9d8e003eafd.png)

**Comment by kapiswayprakhar15** [comment]
you may also see from branch 'Prakhar'
